-- CREATE OR REPLACE FUNCTION GEN_CARD_NO
-- RETURN VARCHAR2 IS 
--     V_CARD VARCHAR2(20):= NULL;

-- BEGIN
--     SELECT CARD_NO INTO V_CARD 
--     FROM(SELECT DISTINCT CARD_NO FROM BORROWER
--     WHERE ROWNUM < 201
--     ORDER BY DBMS_RANDOM.VALUE)
--     WHERE ROWNUM = 1; 

--     RETURN V_CARD;
-- END;


-- CREATE OR REPLACE FUNCTION GEN_BOOK_ID
-- RETURN VARCHAR2 IS 
--     V_BOOK VARCHAR2(20):= NULL;

-- BEGIN
--     SELECT BOOK_ID INTO V_BOOK 
--     FROM(SELECT DISTINCT BOOK_ID FROM BOOKS_HAVE_COPIES
--     WHERE ROWNUM < 101
--     ORDER BY DBMS_RANDOM.VALUE)
--     WHERE ROWNUM = 1; 

--     RETURN V_BOOK;
-- END;

-- CREATE OR REPLACE FUNCTION GEN_DT_OUT
-- RETURN DATE IS 
--     V_DATE DATE;
    
-- BEGIN
--     SELECT (TRUNC(TO_DATE('31/10/2020','DD/MM/YYYY') + DBMS_RANDOM.VALUE * 364)) 
--     INTO V_DATE 
--     FROM DUAL;
    
--     RETURN V_DATE;
-- END;

CREATE OR REPLACE FUNCTION get_available_copies(
    p_book_id IN BOOKS_HAVE_COPIES.BOOK_ID%TYPE,
    p_branch_id IN BOOKS_HAVE_COPIES.BRANCH_ID%TYPE
) RETURN NUMBER AS
    v_available_copies NUMBER;
BEGIN
    SELECT AVAILIABLE_COPIES INTO v_available_copies
    FROM BOOKS_HAVE_COPIES
    WHERE BOOK_ID = p_book_id AND BRANCH_ID = p_branch_id;
    
    RETURN v_available_copies;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
